name: GitHub Actions Maven Build
on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2
      - name: 'Step 2 - Create api key and Google credentials'
        run: |
          echo '${{ secrets.API_KEY }}' | base64 --decode > api_key.json
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' | base64 --decode > my-project-1521814632192-74db441a7e07.json
          echo '${{ secrets.APPLICATION_PROPERTIES }}' | base64 --decode > BestMoviesAPI/main/resources/application.properties
      - name: Step 3 - Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Step 4 - Have GitHub Actions Build Maven Project
        run: mvn -B package --file pom.xml
      - name: Step 5 - List the current directory
        run: ls -a
      - name: Step 6 - Run project tests with maven
        run: mvn clean test
